server:
  port: 8081
spring:
  application:
    name: "users"
  profiles:
    active: "qa"
  datasource:
    url: jdbc:mysql://localhost:3306/usersdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: embedded
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  config:
    import: "configserver:http://localhost:8071/"