server:
  port: 8080
spring:
  application:
    name: "books"
  profiles:
    active: "qa"
  datasource:
    url: jdbc:mysql://localhost:3307/booksdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
  config:
    import: "configserver:http://localhost:8071/"